### ISSUE TITLE
Latest version not published

### ISSUE THREAD

**Issue by Christopher-Bradshaw** [michitaro/healpix#17]
Hey Koike,

Thanks for the package - I'm playing around with visualizing some CMB data and find it really useful. Just a quick question - the latest version does not seem to be published to npm. I can work around it by building locally, but thought I would just let you know.

**Comment by michitaro** [comment]
Thank you very much for the notice. I have updated npm repository.
https://www.npmjs.com/package/@hscmap/healpix will be updated soon.

Thank you😀
