### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cdeil** [michitaro/healpix#2]
@michitaro  - Hi, I was looking for a TS / JS HEALPix package, thinking to write one, and now see that you've already done it. Awesome, thanks!

One question concerning license: is it really MIT?
The original C++ lib is GPL, so I assume you didn't copy from there?

**Comment by michitaro** [comment]
I wrote this from scratch, borrowing only API interfaces from healpy.
So yes, this is MIT licensed.

**Comment by cdeil** [comment]
Great, thanks for confirming!
