### ISSUE TITLE
API docs?

### ISSUE THREAD

**Issue by cdeil** [michitaro/healpix#3]
Hi, I'm new to Typescript.

Is there a way to generate API docs?

I see https://github.com/michitaro/healpix#progress but to be able to use it I have to look at the code what the inputs / outputs are. Is that how it's usually done for Typescript?

If there is a way to add docs and you want it here, this could be something I contribute to a bit while I familiarise myself with TS and this package?

**Comment by michitaro** [comment]
I've generated docs by [typedoc](https://github.com/TypeStrong/typedoc ).
https://michitaro.github.io/healpix/typedoc/modules/_index_.html

There are no comments yet.

**Comment by cdeil** [comment]
Thanks!
